### ISSUE TITLE
No mp4 file

### ISSUE THREAD

**Issue by DomTaffuri** [kwangmeng/ionic-screen-recorder#1]
I'm not able to generate the mp4 file. Here my code.

ScreenRecord.startRecord({isAudio : true}, this.file.externalRootDirectory + "/prova.mp4", (res) =>{
      console.log(res);
      ScreenRecord.stopRecord((res) =>{
        console.log(res);
        console.log(this.file.listDir(this.file.externalRootDirectory,""))
      })
    })

**Comment by kwangmeng** [comment]
Hello, i no longer maintain this fork anymore....I believe its related to the Android version issue. So sorry !
