### ISSUE TITLE
App crashes when start recording in Android

### ISSUE THREAD

**Issue by sriram-23** [kwangmeng/ionic-screen-recorder#2]
Hi, App crashes after it prompts for screen recording.
Here is my code:
```
window.ScreenRecord.startRecord({ isAudio: true }, 'file:///data/com.example.survey/video/test.mp4', success, error);
const success = (msg) => {
      console.log('Success: ', msg);
    }
    const error = (err) => {
      console.log('Some Error: ', err);
    }
```
I'm getting the below dialog, but when I click on _START NOW_ it crashes
![Screenshot_20210110-185036](https://user-images.githubusercontent.com/58411349/104124193-65417600-5375-11eb-81d0-2da557e3e468.png)

**Comment by kwangmeng** [comment]
Hello, i no longer maintain this fork anymore....I believe its related to the Android version issue. So sorry !
